name: Deploy of UnBForum Frontend [CI/CD]

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:

jobs:
  cd_unbforum_front:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install dependencies
        run: |
          npm install
      
      - name: Build app
        run: |
          npm run build
      
      - name: Deploy to a new branch
        uses: nicholasgriffintn/github-branch-deployment-action@0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_GITHUB_TOKEN }}
          BRANCH: deploy
          FOLDER: dist
          MESSAGE: 'Build: ({sha}) {msg}'
